version: 1.4.1-SNAPSHOT.{build}

#build C# solution and scala project
build_script:
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: Build.cmd

test:
  assemblies:
    - csharp\AdapterTest\bin\Debug\AdapterTest.dll

# scripts to run after tests
after_test:
  - cmd: Runsamples.cmd --validate --torun DFRddSample --verbose
